version: '3'

services:

    identity-proxy:
        build:
            context: ./identity-proxy
            dockerfile: ./Dockerfile
        #container_name: identity-proxy
        #command: uvicorn identity-proxy:app --host 0.0.0.0 --port 80 --reload
        ports:
          - 8080
        volumes:
          - .:/identity-proxy
#        depends_on:
#          - docker

    tomtomload:
        build:
            context: ./tomtomload
            dockerfile: ./Dockerfile
        #container_name: tomtomload
        #command: uvicorn tomtomload:app --host 0.0.0.0 --port 80 --reload
        ports:
          - "5000"
        volumes:
          - .:/tomtomload
        depends_on:
          - identity-proxy

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - identity-proxy
        ports:
            - "80:80"
